### ISSUE TITLE
Getting undefined method `log_level' for #<Eye::Logger:0x0000000007e3ede0>

### ISSUE THREAD

**Issue by rept** [kostya/eye-rotate#2]
This is my config: 

```
require 'eye-rotate'

Eye.config do
  logger '/websites/nobi/production/current/log/eye.log'
end
Eye.application 'sneakers' do
working_dir "/websites/nobi/production/current/"
trigger :flapping, :times => 10, :within => 1.minute
  env 'RAILS_ENV' => 'production'
process :sneakers do
    daemonize true
    pid_file "/websites/nobi/production/current/tmp/pids/sneakers.pid"
    stdall "/websites/nobi/production/current/log/sneakers.log"
    check :log_rotate, :every => 30.seconds, :count => 5, :gzip => true, :min_size => 1048576

    start_command "bundle exec rake sneakers:run"
    stop_signals [:TERM, 5.seconds, :KILL]
    restart_command 'kill -9 {PID}'

    restart_grace 10.seconds

    check :cpu, :every => 30, :below => 80, :times => 3
    check :memory, :every => 30, :below => 256.megabytes, :times => [3,5]
  end
end

```

I'm getting this error message:

NoMethodError: undefined method `log_level' for #<Eye::Logger:0x0000000007e3ede0>

Should this gem still be working?

**Comment by kostya** [comment]
just tested in ruby 2.3.1 works fine, eye v0.10.0. what ruby and eye you use?

**Comment by rept** [comment]
@kostya thanks for your reply.  Ruby 2.6 and eye v0.10.0.

**Comment by rept** [comment]
Hi @kostya  any idea why this doesn't work on later Ruby?  The status of Ruby 2.3 is end-of-life.

**Comment by kostya** [comment]
just installed 2.6.3 and test is with such config, all work is ok:
```ruby
require 'eye-rotate'

Eye.config do
  logger '/tmp/eye.log'
end

Eye.application 'sneakers' do
  working_dir "/tmp/"
  process :sneakers do
    daemonize true
    pid_file "sneakers.pid"
    stdall "sneakers.log"
    check :log_rotate, :every => 30.seconds, :count => 5, :gzip => true, :min_size => 1048576
    start_command "ruby -e 'loop do; sleep 1.0; puts :work; end;'"
    stop_signals [:TERM, 5.seconds, :KILL]
    restart_command 'kill -9 {PID}'
    restart_grace 10.seconds
    check :cpu, :every => 30, :below => 80, :times => 3
    check :memory, :every => 30, :below => 256.megabytes, :times => [3,5]
  end
end
```

`bundle exec eye load 1.rb -f`

**Comment by kostya** [comment]
try to run eye with `-f` flag to better see errors

**Comment by rept** [comment]
Hi @kostya 

I'm getting this on rake assets:precompile as soon as I add eye-rotate as a gem.

1) It deploys fine to a docker.
2) I only make one modification: I add the gem 'eye-rotate' and do bundle install
3) when I deploy again to docker I get a fail on the assets:precompile (see full stacktrace below).

Does this help at all?

```
rake aborted!
NoMethodError: undefined method `log_level' for #<Eye::Logger:0x0000561e47cc8bf0>
Did you mean?  log_ex
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/logger/delayed.rb:26:in `initialize'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/logger/delayed.rb:17:in `new'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/logger/delayed.rb:17:in `install!'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:1230:in `catch_error'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:795:in `try_declaration'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:732:in `declaration_or_ruleset'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:697:in `block_child'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:686:in `block_contents'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:678:in `block'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:246:in `mixin_directive'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:234:in `special_directive'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:209:in `directive'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:696:in `block_child'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:689:in `block_contents'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:137:in `stylesheet'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/scss/parser.rb:41:in `parse'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/engine.rb:414:in `_to_tree'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/engine.rb:321:in `to_tree'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:323:in `block in visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:88:in `block in with_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:135:in `with_frame'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:88:in `with_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:79:in `block in with_base'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:135:in `with_frame'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:79:in `with_base'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:158:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:325:in `map'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:88:in `block in with_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:135:in `with_frame'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:88:in `with_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:79:in `block in with_base'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:135:in `with_frame'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:79:in `with_base'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:158:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:325:in `map'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:88:in `block in with_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:135:in `with_frame'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:88:in `with_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:79:in `block in with_base'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:135:in `with_frame'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/stack.rb:79:in `with_base'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:158:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:52:in `map'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/base.rb:36:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:157:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/visitors/perform.rb:10:in `visit'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/root_node.rb:36:in `css_tree'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/tree/root_node.rb:20:in `render'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-3.6.0/lib/sass/engine.rb:290:in `render'
/usr/local/rvm/gems/ruby-2.6.3/gems/sass-rails-5.0.7/lib/sass/rails/template.rb:47:in `evaluate'
/usr/local/rvm/gems/ruby-2.6.3/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/context.rb:99:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/context.rb:129:in `depend_on_asset'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/context.rb:160:in `link_asset'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:27:in `compute_asset_path'
/usr/local/rvm/gems/ruby-2.6.3/gems/actionview-5.2.1/lib/action_view/helpers/asset_url_helper.rb:200:in `asset_path'
/home/app/webapp/app/assets/javascripts/serviceworker.js.erb:14:in `_evaluate_template'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/erb_processor.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/erb_processor.rb:13:in `call'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/usr/local/rvm/gems/ruby-2.6.3/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/usr/local/rvm/gems/ruby-2.6.3/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by kostya** [comment]
try to set in group in Gemfile, this would not require it by default:
```ruby
group(:eye) do
  gem 'eye'
  gem 'eye-rotate'
end
```

**Comment by rept** [comment]
Hi Kostya,

That works!!!  For eye it wasn't necessary, as soon as I include the eye-rotate I need to do it like you write in order for it to work.  Does this impact anything?

Will test the rest now.

**Comment by kostya** [comment]
its no matter, how add this gems, bundler just require all gems not in groups by default, you not need to require eye, because it system tool.
